#!/usr/bin/env python3
from flask import Flask, request, abort
import nanopy.rpc as rpc
import json

rpc.url='http://localhost:55000'

app = Flask(__name__)

@app.route('/')
def index():
    return "Print enabled rpc calls and other stats here"

@app.route('/', methods=['POST'])
def create_task():
    query=json.loads(request.data)
    if not 'action' in query:
        abort(400)
    rpc_call = getattr(rpc, query['action'])
    response = json.dumps(rpc_call())
    return response, 201

if __name__ == '__main__':
    app.run()
